### Basic Array Operations:
1. Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean, and standard deviation of the array.
2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.
3. Generate two 2x3 arrays with random integers and perform element-wise addition, subtraction, multiplication, and division.
4. Create a 4x4 identity matrix.
5. *Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.*

### Array Manipulation:
6. Reshape a 1D array of 12 elements into a 3x4 matrix.
7. Flatten a 3x3 matrix into a 1D array.
8. Stack two 3x3 matrices horizontally and vertically.
9. Concatenate two arrays of different sizes along a new axis.
10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.

### Indexing and Slicing:
11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.
12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.
13. Replace all elements in a 1D array greater than 10 with the value 10.
14. *Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].*
15. Create a 1D array of 10 elements and reverse it using slicing.

### Broadcasting:
16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.
17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.
18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.
19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
20. *Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.*

### Vectorized Operations:
21. Compute the square root of each element in a 2D array using vectorized operations.
22. Calculate the dot product of two 1D arrays of size 5.
23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.
24. Create a 2D array and apply a vectorized operation to double the value of each element.
25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.

### Linear Algebra:
26. Create a 3x3 matrix and find its determinant.
27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.
28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.
29. *Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.*
30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components.
Givecodes to them in python 

In [4]:
import numpy as np

In [5]:
#create a 3x3 array filled with random integers btw 0 an 10
arr=np.random.randint(0,11,(3,3))
print(arr.shape)
print(arr)

(3, 3)
[[ 5  0  7]
 [ 7 10  3]
 [ 3  4  0]]


In [6]:
#create a 1D array of 10 elements and compute the cumulative sum
a=np.arange(1,11)
print('array:\n',a)
print("cumulative sum:")
print(np.cumsum(a))

array:
 [ 1  2  3  4  5  6  7  8  9 10]
cumulative sum:
[ 1  3  6 10 15 21 28 36 45 55]


In [7]:
#generate two 2x3 arrays with random integers and perform element wise operations
a1=np.random.randint(0,10,(2,3))
a2=np.random.randint(0,10,(2,3))
print(a1,a2)
print("addition:",a1+a2)
print("subtraction:",a1-a2)
print("multiplication:",a1*a2)
print("division:",a1/a2)

[[6 8 0]
 [3 2 5]] [[4 8 6]
 [7 8 5]]
addition: [[10 16  6]
 [10 10 10]]
subtraction: [[ 2  0 -6]
 [-4 -6  0]]
multiplication: [[24 64  0]
 [21 16 25]]
division: [[1.5        1.         0.        ]
 [0.42857143 0.25       1.        ]]


In [8]:
#create 4x4 identity matrix
i=np.eye(4)
print("identity matrix:\n",i)

identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.
a = np.array([5, 10, 15, 20, 25])
print("\nDivided by 5:", a / 5)


Divided by 5: [1. 2. 3. 4. 5.]


In [10]:
#Reshape a 1D array of 12 elements into a 3x4 matrix.
a3=np.arange(12)
r=a3.reshape(3,4)
print(r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
#Flatten a 3x3 matrix into a 1D array.
f=r.flatten()
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
#Stack two 3x3 matrices horizontally and vertically.
a4=np.random.randint(0,10,(3,3))
a5=np.random.randint(0,10,(3,3))
print("horizontal stack:\n",np.hstack((a4,a5)))
print("vertical stack:\n",np.vstack((a4,a5)))

horizontal stack:
 [[1 8 2 2 8 4]
 [2 4 1 1 2 7]
 [7 8 2 2 1 1]]
vertical stack:
 [[1 8 2]
 [2 4 1]
 [7 8 2]
 [2 8 4]
 [1 2 7]
 [2 1 1]]


In [13]:
#Concatenate two arrays of different sizes along a new axis.
a6=np.array([1,2,3])
a7=np.array([3,4])
np.concatenate((a6,a7),axis=0)

array([1, 2, 3, 3, 4])

In [14]:
#Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.
t=np.array([[0,0,1],[1,2,4]])
print(t)
print("transposed:\n",t.T)

[[0 0 1]
 [1 2 4]]
transposed:
 [[0 1]
 [0 2]
 [1 4]]


In [15]:
#Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.
f=np.arange(0,16)
f[2:11:2]

array([ 2,  4,  6,  8, 10])

In [16]:
#Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.
ar = np.random.randint(0, 100, (5, 5))
print("\n5x5 Matrix:\n", ar)
print("Sub-matrix:\n", ar[1:4, 2:5])


5x5 Matrix:
 [[57 72 60 85  4]
 [87  5 65 29 55]
 [33 15 74  9 52]
 [85 52 81 82 34]
 [35 51 40  7 70]]
Sub-matrix:
 [[65 29 55]
 [74  9 52]
 [81 82 34]]


In [17]:
#Replace all elements in a 1D array greater than 10 with the value 10.
ar[ar>10]=10
print(ar)

[[10 10 10 10  4]
 [10  5 10 10 10]
 [10 10 10  9 10]
 [10 10 10 10 10]
 [10 10 10  7 10]]


In [18]:
#Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].
fi=np.random.randint(0,10,(10,))
fi[[0,2,4,6]]


array([8, 3, 7, 5])

In [19]:
#Create a 1D array of 10 elements and reverse it using slicing.
fi=np.random.randint(0,10,(10,))
fi[::-1]

array([4, 6, 6, 8, 1, 0, 0, 0, 8, 7])

In [20]:
#Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.
a = np.random.randint(0, 10, (3, 3))
ar = np.array([1, 2, 3])
print("\nBroadcasted Addition:\n", a + ar)


Broadcasted Addition:
 [[ 4 11 11]
 [ 1  4  6]
 [ 9  4  6]]


In [21]:
#Multiply a 1D array of 5 elements by a scalar value using broadcasting.
ar*5

array([ 5, 10, 15])

In [22]:
#Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.
o = np.random.randint(0, 10, (3, 3))
t = np.array([[1], [2], [3]])
print(o)
print(t)
print("\nBroadcasted Subtraction:\n", o-t)

[[3 0 4]
 [9 4 1]
 [8 2 3]]
[[1]
 [2]
 [3]]

Broadcasted Subtraction:
 [[ 2 -1  3]
 [ 7  2 -1]
 [ 5 -1  0]]


In [23]:
#Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.
print(o+20)

[[23 20 24]
 [29 24 21]
 [28 22 23]]


In [24]:
#Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.
f = np.arange(4).reshape(4, 1)
o = np.arange(5).reshape(1, 5)
print("\nBroadcasted Addition:\n", f + o)


Broadcasted Addition:
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [25]:
#Compute the square root of each element in a 2D array using vectorized operations.
sq=np.random.randint(1,100,(2,3))
print(np.sqrt(sq))

[[9.94987437 6.78232998 7.14142843]
 [8.48528137 9.89949494 9.64365076]]


In [26]:
#Calculate the dot product of two 1D arrays of size 5.
d1=np.array([2,2,4,6,7])
d2=np.arange(0,5)
np.dot(d1,d2)

56

In [27]:
#Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.
print(d1>d2)

[ True  True  True  True  True]


In [28]:
#Create a 2D array and apply a vectorized operation to double the value of each element.
sq=np.random.randint(1,100,(2,3))
sq*2

array([[164,  12,  84],
       [160, 122, 108]])

In [29]:
#Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.
h=np.arange(0,100)
np.sum(h[h%2==0])


2450

In [30]:
#Create a 3x3 matrix and find its determinant.
h=np.random.randint(0,100,(3,3))
np.linalg.det(h)


277314.0000000001

In [31]:
#Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.
i = np.array([[4, 7], [2, 6]])
inverse = np.linalg.inv(i)
print("\nInverse Matrix:\n", inverse)
print("Verification:\n", np.dot(i, inverse))



Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Verification:
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [32]:
#Calculate the eigenvalues and eigenvectors of a 2x2 matrix.
val, vec = np.linalg.eig(i)
print("\nEigenvalues:", val)
print("Eigenvectors:\n", vec)


Eigenvalues: [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [33]:
#Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.
coefficients = np.array([[2, 3], [4, 6]])
constants = np.array([5, 10])


solution, residuals, rank, s = np.linalg.lstsq(coefficients, constants, rcond=None)
print("\nLeast-squares solution:", solution)



Least-squares solution: [0.76923077 1.15384615]


In [34]:
#Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components. Givecodes to them in python
arr27 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


U, S, Vt = np.linalg.svd(arr27)


reconstructed = U @ np.diag(S) @ Vt
print("\nReconstructed Matrix:\n", reconstructed)



Reconstructed Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
